[default_session]
preview_command = "lsd --icon always --color always {}"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "âš™ï¸ Dotfiles"
path = "~/.dotfiles"
startup_command = "dotls"

[[session]]
name = "âš™ï¸ Nix config"
path = "~/nixos-config"
startup_command = "nvim flake.nix"
preview_command = "tree ~/nixos-config"

[[session]]
name = "ğŸ’» Develop environments"
path = "~/dev/microservices/developer-environments"
preview_command = "onefetch {}"
startup_command = "docker ps && just --list"
