
[font]
size = 14.0

# ğŸ˜„ ğŸ± ğŸ‘†

[font.normal]
family = "monospace"
style = "regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]
